name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        cc: [ clang, gcc ]
        make: [ bmake, pmake ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies
      run: sudo apt-get install pmake bmake

    - name: make
      run: ${{ matrix.make }} -r -j 2 CC=${{ matrix.cc }}

    - name: install
      run: ${{ matrix.make }} -r -j 2 PREFIX=/tmp/p install
